server:
  port: 8070

spring:
  application:
    name: calculator

  jackson:
    # 格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8

  datasource:
    username: root
    password: fzzhy2003
    url: jdbc:mysql://localhost:3306/calculator?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 30000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
